# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

Metrics/AbcSize:
  Max: 129
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/AbcSize:
  Max: 30
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 385
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/ModuleLength:
  Max: 1350
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 250 # TODO this should be lower for new code
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/CyclomaticComplexity:
  Max: 29
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/CyclomaticComplexity:
  Max: 13 # TODO this should be lower for new code
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 160
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 30 # TODO this should be lower for new code
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/PerceivedComplexity:
  Max: 34
  Exclude:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

Metrics/PerceivedComplexity:
  Max: 14 # TODO this should be lower for new code
  Include:
    - 'src/lib/**/*.rb' # be more strict for new code in lib

# be more strict than rubocop, 5 is too much
Metrics/ParameterLists:
  Max: 4

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Include:
    - 'src/lib/**/*.rb' # force well documented code only for new code

Naming/FileName:
  Include:
    - 'src/lib/**/*.rb' # force correct names on new code

# JR: I found lambda easier to read and understand than ->()
Style/Lambda:
  Enabled: false

Naming/MethodName:
  Include:
    - 'src/lib/**/*.rb' # force correct names on new code

Naming/VariableName:
  Include:
    - 'src/lib/**/*.rb' # force known variables only for new code

# method_alias is safer and more predictable
Style/Alias:
  EnforcedStyle: prefer_alias_method

# this needs more testing if we can have frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
